apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "tripstorm.fullname" . }}-external-mysql-service
  namespace: {{ .Values.namespace }}
  {{- template "tripstorm.labels" . }}
subsets:
- addresses:
  - ip: {{ .Values.databaseEndpointIP }}
  ports:
  - name: {{ .Values.databasePortName }}
    port: {{ .Values.databasePort }}
