apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tripstorm.fullname" . }}-api-deployment
  namespace: {{ .Values.namespace }}
  {{- template "tripstorm.labels" . }}
spec:
  replicas: {{ .Values.apiReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "tripstorm.name" . }}-api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tripstorm.name" . }}-api
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ template "tripstorm.fullname" . }}-image-pull-secret
      containers:
      - name: {{ template "tripstorm.name" . }}-api
        image: {{ .Values.imageCredentials.registry }}/{{ .Values.apiImage }}:{{ .Values.apiImageTag }}
        imagePullPolicy: {{ .Values.apiImagePullPolicy }}
        ports:
        - containerPort: {{ .Values.apiContainerPort }}
          protocol: TCP
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: {{ template "tripstorm.fullname" . }}-secrets
              key: secret-key-base
        - name: DB_HOST
          value: {{ template "tripstorm.fullname" . }}-external-mysql-service
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "tripstorm.fullname" . }}-secrets
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "tripstorm.fullname" . }}-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "tripstorm.fullname" . }}-secrets
              key: db-password
        - name: BRAINTREE_MERCHANT_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "tripstorm.fullname" . }}-secrets
              key: braintree-merchant-id
        - name: BRAINTREE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "tripstorm.fullname" . }}-secrets
              key: braintree-public-key
        - name: BRAINTREE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "tripstorm.fullname" . }}-secrets
              key: braintree-private-key
