apiVersion: v1
kind: Service
metadata:
  name: {{ template "tripstorm.name" . }}-ui-service
  namespace: {{ .Release.Namespace }}
  {{- template "tripstorm.labels" . }}
spec:
  ports:
  - name: {{ .Values.uiServicePortName }}
    port: {{ .Values.uiServicePort }}
    protocol: TCP
    targetPort: {{ .Values.uiServiceTargetPort }}
  selector:
    app: {{ template "tripstorm.name" . }}-ui
    release: {{ .Release.Name }}
  type: ClusterIP
