apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tripstorm.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  {{- template "tripstorm.labels" . }}
type: Opaque
data:
  secret-key-base: {{ .Values.secretKeyBase | b64enc }}
  db-name: {{ .Values.dbName | b64enc }}
  db-user: {{ .Values.dbUser | b64enc }}
  db-password: {{ (required "A dbPassword is required!" .Values.dbPassword) | b64enc }}
  braintree-merchant-id: {{ .Values.braintreeMerchantId | b64enc }}
  braintree-public-key: {{ .Values.braintreePublicKey | b64enc }}
  braintree-private-key: {{ .Values.braintreePrivateKey | b64enc }}
  stripe-api-key: {{ (required "A stripeApiKey is required!" .Values.stripeApiKey) | b64enc }}
