apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "tripstorm.fullname" . }}-ui-deployment
  namespace: {{ .Release.Namespace }}
  {{- template "tripstorm.labels" . }}
spec:
  replicas: {{ .Values.uiReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "tripstorm.name" . }}-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tripstorm.name" . }}-ui
        release: {{ .Release.Name }}
      annotations:
        timestamp: "{{ .Release.Time.Seconds }}"
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ template "tripstorm.fullname" . }}-image-pull-secret
      containers:
      - name: {{ template "tripstorm.name" . }}-ui
        image: {{ .Values.imageCredentials.registry }}/{{ .Values.uiImage }}:{{ .Values.uiImageTag }}
        imagePullPolicy: {{ .Values.uiImagePullPolicy }}
        ports:
        - containerPort: {{ .Values.uiContainerPort }}
          protocol: TCP
