apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tripstorm.fullname" . }}-image-pull-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- template "tripstorm.labels" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
