---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "tripstorm_traefik.fullname" . }}-ingress-controller
  namespace: {{ .Values.namespace }}
  {{- template "tripstorm_traefik.labels" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "tripstorm_traefik.fullname" . }}-ingress-controller
        release: {{ .Release.Name }}
    spec:
      hostNetwork: true # this sucks but is necessary for now
      serviceAccountName: {{ template "tripstorm_traefik.fullname" . }}-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: {{ template "tripstorm_traefik.fullname" . }}-conf
        - name: acme
          hostPath:
            type: FileOrCreate
            path: /etc/traefik/acme.json
      containers:
      - args:
        - --kubernetes
        - --logLevel=ERROR
        - --configfile=/config/traefik.toml
        image: {{ .Values.imageName }}
        name: {{ template "tripstorm_traefik.fullname" . }}-ingress-controller
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/config"
            name: config
          - mountPath: "/acme/acme.json"
            name: acme
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE

