apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grez.name" . }}-nfs-assets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
  labels:
    {{- include "grez.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}

