apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grez.name" . }}-file-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grez.labels" . | nindent 4 }}
data:
  paypal_production_cert: {{ .Values.fileSecrets.paypal_production_cert | b64enc }}
type: Opaque

