apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grez.name" . }}-nginx-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grez.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        client_max_body_size 20m;

        sendfile        on;
        keepalive_timeout  65;

        upstream webapp {
            server 127.0.0.1:3000;
        }

        server {
            listen 80;

            location / {
                proxy_pass         http://webapp;
                proxy_redirect     off;
            }
        }
    }

