apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grez.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grez.labels" . | nindent 4 }}
data:
  mysql_password: {{ .Values.secrets.mysql_password | b64enc }}
  mysql_username: {{ .Values.secrets.mysql_username | b64enc }}
  paypal_pass: {{ .Values.secrets.paypal_pass | b64enc }}
  paypal_user: {{ .Values.secrets.paypal_user | b64enc }}
  rooms_password: {{ .Values.secrets.rooms_password | b64enc }}
  rooms_username: {{ .Values.secrets.rooms_username | b64enc }}
  smtp_password: {{ .Values.secrets.smtp_password | b64enc }}
  smtp_username: {{ .Values.secrets.smtp_username | b64enc }}
type: Opaque

