apiVersion: v1
kind: Service
metadata:
  name: {{ include "grez.name" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grez.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ include "grez.name" . }}

