apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roomify.name" . }}-nginx-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "roomify.labels" . | nindent 4 }}
data:
  default.conf: |-
    upstream rails_app {
       server 127.0.0.1:3000;
    }
    server {
       # define your domain
       # server_name www.example.com;
       # define the public application root
       root   /var/www/app/public;
       index  index.html;
       # define where Nginx should write its logs
       access_log /var/www/app/log/nginx.access.log;
       error_log /var/www/app/log/nginx.error.log;

       rewrite  ^/$  /index.html  last;

       # deny requests for files that should never be accessed
       location ~ /\. {
          deny all;
       }
       location ~* ^.+\.(rb|log)$ {
          deny all;
       }

       # serve static (compiled) assets directly if they exist (for rails production)
       location ~ ^/(bower_components|images|scripts|styles|views)/ {
          try_files $uri @rails;
          access_log on;
          gzip_static on;
          # to serve pre-gzipped version
          expires max;
          add_header Cache-Control public;

          add_header Last-Modified "";
          add_header ETag "";
          break;
       }

       # send non-static file requests to the app server
       location / {
          try_files $uri @rails;
       }
       location @rails {
          proxy_set_header  X-Real-IP  $remote_addr;
          proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://rails_app;
       }
    }
