apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roomify.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "roomify.labels" . | nindent 4 }}
data:
  db_password: {{ .Values.secrets.db_password | b64enc }}
  db_user: {{ .Values.secrets.db_user | b64enc }}
  secret_key_base: {{ .Values.secrets.secret_key_base | b64enc }}
  smtp_username: {{ .Values.secrets.smtp_username | b64enc }}
  smtp_password: {{ .Values.secrets.smtp_password | b64enc }}
type: Opaque
